[package]
name = "pprouter"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
bytes = "1"
tls-parser = "0.11" # Use the latest compatible version
nom = "7" # Required by tls-parser
futures = "0.3" 